/// Uygulama genelinde kullanılan sabit kitap kategorileri listesi.
const List<String> kBookCategories = [
  "Deneme",
  "Araştırma-İnceleme",
  "Anı-Mektup",
  "Söyleşi",
  "Gezi",
  "Tarih",
  "Roman",
  "Hikaye",
  "Oyun",
  "Şiir",
  "Bilim",
  "Psikoloji",
  "Kişisel Gelişim",
  "Polisiye",
  "Bilimkurgu",
  "Dini Hikaye",
  "Tefsir",
  "Hadis",
  "Siyer",
  "Kelam",
  "Felsefe-Düşünce",
  "Sosyoloji",
  "Biyografi-Otobiyografi",
  "Sempozyum",
  "Sanat",
  "Müzik",
  "Mimari",
  "Spor",
  "Satranç",
  "Tasavvuf",
  "Mesnevi",
  "Siyaset",
  "Dergi",
  "Edebiyat",
  "Gastronomi",
  "Moda",
  "İlmihal",
  "Sözlük",
  "Çizgi-roman",
  "Grafik Hibrit",
  "Sağlık",
  "Belge Roman",
  "Tarihi Roman",
  "Mizah",
];
